-- eliminar_estructura.sql
-- ---------------------------------------
-- Descripcion: Elimina la estructura basica 
-- Fecha: Dic-2023
-- Autor: Alvaro Anaya
-- ---------------------------------------
-- ELIMINAMOS USUARIOS
DROP USER USER1 CASCADE;
DROP USER USER2 CASCADE;
DROP USER USER3 CASCADE;
DROP USER USER4 CASCADE;
DROP USER AJENO1 CASCADE;

-- ELIMINAMOS TABLESPACES
DROP TABLESPACE USER1TS INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE USER2TS INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE USER3TS INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE USER4TS INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE COMUNTS INCLUDING CONTENTS AND DATAFILES;



